name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Checkout ZMK Repository
        uses: actions/checkout@v3
        with:
          repository: andreasnonslid/zmk
          ref: main
          path: src

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cachix
        run: |
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use moergo-glove80-zmk-dev

      - name: Build Glove80 combined firmware
        run: nix-build config -o combined

      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: glove80.uf2
          path: glove80.uf2
